/* ============================================================
 * MechaXMatch スタンドアロン版 — ダミーデータ
 * (src/lib/data/*.ts から自動変換。Next.js版と同一内容)
 * ============================================================ */

/* ---------- skills ---------- */
/** スキル10種類。tierはスキルツリー上の段(1=基礎, 2=応用, 3=総合) */
const SKILLS = [
    { id: "drawing", name: "図面読解", icon: "📐", color: "#22d3ee", tier: 1, description: "図面の投影法・寸法・記号を正しく読み取る力" },
    { id: "materials", name: "材料力学", icon: "🧱", color: "#fbbf24", tier: 1, description: "応力・ひずみ・強度計算などの基礎力学" },
    { id: "measurement", name: "実験・計測", icon: "🔬", color: "#4ade80", tier: 1, description: "ノギス・マイクロメータ等での計測とデータ整理" },
    { id: "electronics", name: "電子工作", icon: "🔌", color: "#f472b6", tier: 1, description: "回路の読解・はんだ付け・センサ活用" },
    { id: "cad", name: "CAD", icon: "🖥️", color: "#a78bfa", tier: 2, description: "3D CADでのモデリング・図面化・データ修正" },
    { id: "machining", name: "加工知識", icon: "⚙️", color: "#fb923c", tier: 2, description: "切削・板金・3Dプリンタなど加工法の選定力" },
    { id: "control", name: "制御", icon: "🎛️", color: "#38bdf8", tier: 2, description: "PLC・シーケンス制御・メカトロの基礎" },
    { id: "report", name: "レポート作成", icon: "📝", color: "#e2e8f0", tier: 2, description: "技術文書として伝わるレポートを書く力" },
    { id: "aidx", name: "AI/DX", icon: "🤖", color: "#c084fc", tier: 3, description: "AI活用・データ分析・現場のDX推進" },
    { id: "teamdev", name: "チーム開発", icon: "🤝", color: "#34d399", tier: 3, description: "役割分担・進捗共有・複数学科での協働" },
];
const SKILL_MAP = Object.fromEntries(SKILLS.map((s) => [s.id, s]));
/** スキルレベル計算: レベルnに必要な累計スキル経験値 = 60 * n * (n-1) / 2 */
function skillLevel(xp) {
    let level = 1;
    while (xp >= (60 * level * (level + 1)) / 2)
        level++;
    return level;
}
function skillLevelProgress(xp) {
    const level = skillLevel(xp);
    const prevThreshold = (60 * (level - 1) * level) / 2;
    const nextThreshold = (60 * level * (level + 1)) / 2;
    const current = xp - prevThreshold;
    const next = nextThreshold - prevThreshold;
    return { current, next, percent: Math.round((current / next) * 100) };
}

/* ---------- quests ---------- */
/**
 * クエスト(企業から投稿された技術タスク)のダミーデータ。
 * q1〜q15: 学生のクエスト一覧に表示される15件(承認済み中心)
 * p1〜p5 : 教員承認待ちの5件
 */
const QUESTS = [
    {
        id: "q1",
        title: "古い手描き図面を3D CAD化する",
        company: "株式会社タカハシ精機",
        industry: "精密部品加工",
        difficulty: 2,
        recommendedGrade: "3年生以上",
        requiredSkills: ["cad", "drawing"],
        reward: 8000,
        xp: 120,
        deadline: "2026-08-10",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "創業40年の精密部品メーカー。ベテラン設計者が残した手描き図面が300枚以上あり、設変のたびに紙図面を探すのに時間がかかっています。",
        request: "手描き図面(スキャンPDF)10枚を3D CADモデルと2D図面に変換してください。使用CADはFusion 360またはSOLIDWORKSを想定しています。",
        deliverables: ["3D CADデータ(STEP形式)", "2D図面(PDF)", "作業メモ(不明点・判断根拠)"],
        knowledge: ["三角法の読み方", "寸法公差の基礎", "3D CADの基本操作"],
        equipment: ["自宅または学校のPC", "CADソフト(学生ライセンス可)"],
        cautions: ["図面の社外持ち出しは禁止(閲覧は専用リンクのみ)", "不明な寸法は推測せず質問すること"],
        criteria: ["寸法の正確さ", "モデリングの手順の適切さ", "質問・報告のわかりやすさ"],
        referenceMaterialIds: ["m13", "m1"],
        companyRating: 4.6,
        companyRatingCount: 12,
        submissionTemplateId: "t1",
        learnPoints: "実務図面の読み方と、図面からモデルを起こす実践力が身につきます。",
        ndaRequired: true,
    },
    {
        id: "q2",
        title: "溶接治具の改善案を考える",
        company: "北陸溶接工業株式会社",
        industry: "溶接・板金",
        difficulty: 3,
        recommendedGrade: "4年生以上",
        requiredSkills: ["machining", "drawing", "report"],
        reward: 12000,
        xp: 180,
        deadline: "2026-08-25",
        remoteOk: false,
        safetyLevel: "中",
        dangerLabels: ["現場訪問あり", "高温部品あり", "教員立会い推奨"],
        teacherCheckRequired: true,
        approvalStatus: "approved",
        isTeam: false,
        background: "溶接工程でワークの位置決めに時間がかかり、段取り時間が1個あたり15分発生しています。治具の固定方法を見直したいと考えています。",
        request: "現場見学(半日)ののち、現行治具の問題点を整理し、段取り時間を短縮する改善案を2案以上提案してください。",
        deliverables: ["現状分析シート", "改善提案書(スケッチ付き・2案以上)"],
        knowledge: ["治具の基礎", "溶接の熱変形", "トグルクランプ等の位置決め要素"],
        equipment: ["企業の溶接工場(見学)", "学校のPC"],
        cautions: ["工場内では保護具を必ず着用", "溶接作業自体は行いません(見学のみ)"],
        criteria: ["問題点の的確さ", "改善案の実現性", "提案書の説得力"],
        referenceMaterialIds: ["m10", "m15"],
        companyRating: 4.2,
        companyRatingCount: 5,
        submissionTemplateId: "t5",
        learnPoints: "実際の生産現場を見て、治具設計・段取り改善の考え方を学べます。",
        ndaRequired: true,
    },
    {
        id: "q3",
        title: "機械部品の寸法測定レポート作成",
        company: "エヌテック計測株式会社",
        industry: "計測・検査",
        difficulty: 1,
        recommendedGrade: "2年生以上",
        requiredSkills: ["measurement", "report"],
        reward: 5000,
        xp: 80,
        deadline: "2026-07-31",
        remoteOk: false,
        safetyLevel: "低",
        dangerLabels: ["学校設備使用", "工具使用あり"],
        teacherCheckRequired: true,
        approvalStatus: "approved",
        isTeam: false,
        isUrgent: true,
        isPopular: true,
        classmatesChallenging: 3,
        background: "量産部品の抜き取り検査を外部に出す前に、測定手順書のわかりやすさを学生視点で検証したいと考えています。",
        request: "送付する樹脂部品サンプル20個について、指定手順書に従いノギス・マイクロメータで寸法測定し、レポートにまとめてください。手順書のわかりにくい点も指摘してください。",
        deliverables: ["寸法測定レポート(Excel+PDF)", "手順書の改善コメント"],
        knowledge: ["ノギス・マイクロメータの使い方", "有効数字とばらつきの整理"],
        equipment: ["学校の計測器(ノギス・マイクロメータ)"],
        cautions: ["計測器は使用後に必ず清掃・返却", "サンプルは返送が必要です"],
        criteria: ["測定値の信頼性", "レポートの見やすさ", "改善コメントの具体性"],
        referenceMaterialIds: ["m6", "m14"],
        companyRating: 4.8,
        companyRatingCount: 21,
        submissionTemplateId: "t4",
        learnPoints: "計測の基本と、データを他人に伝わる形にまとめる力が身につきます。",
        ndaRequired: false,
    },
    {
        id: "q4",
        title: "3Dプリンタ用データの修正・最適化",
        company: "株式会社プロトラボ金沢",
        industry: "試作・3Dプリント",
        difficulty: 2,
        recommendedGrade: "2年生以上",
        requiredSkills: ["cad", "machining"],
        reward: 6000,
        xp: 100,
        deadline: "2026-08-05",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        isPopular: true,
        classmatesChallenging: 2,
        background: "お客様から入稿されるSTLデータに、肉厚不足・面の破れなどの不備が多く、修正作業が追いついていません。",
        request: "不備のあるSTLデータ8件を修正し、FDM方式で造形可能な状態にしてください。修正方針は1件ごとにメモを残してください。",
        deliverables: ["修正済みSTLデータ", "修正内容メモ"],
        knowledge: ["STLデータの構造", "FDM 3Dプリンタの造形制約(肉厚・オーバーハング)"],
        equipment: ["自宅または学校のPC", "メッシュ編集ソフト(無償ツール可)"],
        cautions: ["お客様データのため取り扱い注意(NDAあり)"],
        criteria: ["造形可能性", "元形状の維持", "修正メモのわかりやすさ"],
        referenceMaterialIds: ["m12"],
        companyRating: 4.4,
        companyRatingCount: 9,
        submissionTemplateId: "t1",
        learnPoints: "3Dプリントの造形制約と、実データの修正テクニックが学べます。",
        ndaRequired: true,
    },
    {
        id: "q5",
        title: "工場の作業手順を動画から手順書に整理",
        company: "白山機工株式会社",
        industry: "産業機械組立",
        difficulty: 2,
        recommendedGrade: "2年生以上",
        requiredSkills: ["report", "aidx"],
        reward: 7000,
        xp: 110,
        deadline: "2026-08-20",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "ベテラン作業者の組立ノウハウが動画でしか残っておらず、新人教育に使える手順書がありません。",
        request: "組立作業動画(約30分×3本)を視聴し、写真キャプチャ付きの作業手順書に整理してください。注意ポイントは目立つように記載してください。",
        deliverables: ["作業手順書(PowerPointまたはPDF)", "気づいた改善点リスト"],
        knowledge: ["作業分解の考え方", "わかりやすい手順書のレイアウト"],
        equipment: ["自宅または学校のPC"],
        cautions: ["動画の複製・SNS投稿は禁止"],
        criteria: ["手順の抜け漏れのなさ", "初心者へのわかりやすさ", "危険ポイントの明示"],
        referenceMaterialIds: ["m15"],
        companyRating: 4.0,
        companyRatingCount: 7,
        submissionTemplateId: "t6",
        learnPoints: "現場ノウハウの文書化という、DXの第一歩となるスキルが学べます。",
        ndaRequired: true,
    },
    {
        id: "q6",
        title: "搬送ユニットの簡易強度計算",
        company: "加賀オートメーション株式会社",
        industry: "FA・自動化設備",
        difficulty: 4,
        recommendedGrade: "4年生以上",
        requiredSkills: ["materials", "drawing", "report"],
        reward: 15000,
        xp: 250,
        deadline: "2026-09-15",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: true,
        approvalStatus: "approved",
        isTeam: false,
        background: "小型搬送ユニットの新規設計にあたり、フレームのたわみと支持ボルトの強度を事前に確認しておきたいと考えています。",
        request: "支給する構想図と荷重条件をもとに、片持ちフレームのたわみ計算と、ボルトのせん断・引張の簡易計算を行い、計算書にまとめてください。",
        deliverables: ["強度計算書(計算過程を明記)", "計算の前提条件リスト"],
        knowledge: ["はりのたわみ公式", "許容応力と安全率", "ボルトの強度区分"],
        equipment: ["自宅または学校のPC"],
        cautions: ["計算結果はそのまま設計採用されるものではありません(検証目的)"],
        criteria: ["計算過程の正しさ", "前提条件の明示", "単位系の一貫性"],
        referenceMaterialIds: ["m1", "m2", "m3"],
        companyRating: 4.5,
        companyRatingCount: 8,
        submissionTemplateId: "t3",
        learnPoints: "授業で学んだ材料力学が実際の設計にどう使われるかを体験できます。",
        ndaRequired: true,
    },
    {
        id: "q7",
        title: "ボルト選定の妥当性チェック",
        company: "株式会社タカハシ精機",
        industry: "精密部品加工",
        difficulty: 3,
        recommendedGrade: "3年生以上",
        requiredSkills: ["materials", "drawing"],
        reward: 9000,
        xp: 150,
        deadline: "2026-08-30",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "既存設備の改造で締結部の荷重条件が変わったため、現行ボルト(M8×4本)のままで問題ないか第三者視点で確認したいです。",
        request: "荷重条件と締結部の図面をもとに、ボルトの本数・サイズ・強度区分の妥当性をチェックし、必要なら代替案を提示してください。",
        deliverables: ["ボルト選定チェックシート", "代替案(必要な場合)"],
        knowledge: ["ボルトの強度区分と許容荷重", "締付けトルクと軸力の関係"],
        equipment: ["自宅または学校のPC"],
        cautions: ["最終判断は企業側の設計責任者が行います"],
        criteria: ["チェック観点の網羅性", "計算根拠の明確さ"],
        referenceMaterialIds: ["m3", "m4"],
        companyRating: 4.6,
        companyRatingCount: 12,
        submissionTemplateId: "t3",
        learnPoints: "ボルト1本にも計算根拠があることを、実際の案件で体感できます。",
        ndaRequired: false,
    },
    {
        id: "q8",
        title: "切削しやすい形状への設計改善提案",
        company: "小松マシンパーツ株式会社",
        industry: "機械加工",
        difficulty: 3,
        recommendedGrade: "3年生以上",
        requiredSkills: ["machining", "cad", "drawing"],
        reward: 10000,
        xp: 160,
        deadline: "2026-09-05",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "お客様支給の部品図面に、深い止まり穴や鋭利な内隅など加工コストが上がる形状が多く、提案営業の材料が欲しいと考えています。",
        request: "部品図面5点について「加工しにくい箇所」を指摘し、機能を保ったまま加工しやすくする形状変更案を提案してください。",
        deliverables: ["加工性チェックリスト", "改善提案書(Before/Afterスケッチ付き)"],
        knowledge: ["エンドミル加工の基礎", "内隅Rと工具径の関係", "止まり穴・貫通穴のコスト差"],
        equipment: ["自宅または学校のPC", "CADソフト(任意)"],
        cautions: ["機能・強度を損なう変更は不可"],
        criteria: ["指摘の的確さ", "提案の実現性", "コスト意識"],
        referenceMaterialIds: ["m11", "m12"],
        companyRating: 4.3,
        companyRatingCount: 6,
        submissionTemplateId: "t5",
        learnPoints: "「作りやすい設計(DFM)」の視点が身につき、設計者として一段成長できます。",
        ndaRequired: true,
    },
    {
        id: "q9",
        title: "制御盤のPLC配線チェックリスト作成",
        company: "北陸電機制御株式会社",
        industry: "制御盤製作",
        difficulty: 4,
        recommendedGrade: "4年生以上",
        requiredSkills: ["control", "electronics", "report"],
        reward: 13000,
        xp: 220,
        deadline: "2026-09-20",
        remoteOk: false,
        safetyLevel: "高",
        dangerLabels: ["現場訪問あり", "高電圧注意", "教員立会い推奨"],
        teacherCheckRequired: true,
        approvalStatus: "approved",
        isTeam: false,
        background: "制御盤の出荷前検査で配線ミスの見逃しが年に数件発生しており、チェック手順の標準化を進めています。",
        request: "電気図面とPLCのI/O表を照合し、検査担当者が使える配線チェックリストを作成してください。現場見学で実機を確認できます(通電作業はありません)。",
        deliverables: ["配線チェックリスト(Excel)", "チェック手順の説明資料"],
        knowledge: ["シーケンス図の読み方", "PLCのI/O割付", "制御盤の基本構成"],
        equipment: ["企業の検査場(見学)", "学校のPC"],
        cautions: ["通電状態の盤には絶対に触れないこと", "見学時は教員または企業担当者が立会います"],
        criteria: ["チェック項目の網羅性", "現場で使いやすい構成"],
        referenceMaterialIds: ["m8"],
        companyRating: 4.1,
        companyRatingCount: 4,
        submissionTemplateId: "t6",
        learnPoints: "制御盤の実物と図面を突き合わせる、実務ならではの経験ができます。",
        ndaRequired: true,
    },
    {
        id: "q10",
        title: "家庭用製品の安全レビュー(挟み込み・突起)",
        company: "ホームテック株式会社",
        industry: "生活用品メーカー",
        difficulty: 3,
        recommendedGrade: "3年生以上",
        requiredSkills: ["drawing", "report", "measurement"],
        reward: 8000,
        xp: 140,
        deadline: "2026-08-28",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "新製品(折りたたみ式の物干しスタンド)の量産前に、若い視点も入れた安全レビューを行いたいと考えています。",
        request: "3Dビューデータと試作品写真をもとに、挟み込み・突起・転倒などの危険ポイントを洗い出し、レビューシートにまとめてください。",
        deliverables: ["安全レビューシート", "リスクの優先度づけ"],
        knowledge: ["リスクアセスメントの基礎", "身近な製品事故の事例"],
        equipment: ["自宅または学校のPC"],
        cautions: ["発売前製品のためSNS等への投稿禁止"],
        criteria: ["危険源の抽出数と質", "優先度づけの妥当性"],
        referenceMaterialIds: ["m15"],
        companyRating: 4.7,
        companyRatingCount: 10,
        submissionTemplateId: "t3",
        learnPoints: "設計者に必須の「安全の目」を実製品で鍛えられます。",
        ndaRequired: true,
    },
    {
        id: "q11",
        title: "【レア】ロボットハンド試作機の評価実験",
        company: "未来ロボティクス株式会社",
        industry: "ロボット開発",
        difficulty: 5,
        recommendedGrade: "5年生・専攻科",
        requiredSkills: ["measurement", "control", "report", "materials"],
        reward: 30000,
        xp: 500,
        deadline: "2026-10-10",
        remoteOk: false,
        safetyLevel: "中",
        dangerLabels: ["学校設備使用", "工具使用あり", "回転体あり", "教員立会い推奨"],
        teacherCheckRequired: true,
        approvalStatus: "approved",
        isTeam: false,
        isRare: true,
        classmatesChallenging: 5,
        background: "開発中の柔軟物ハンドリング用ロボットハンドについて、把持力と対象物の損傷の関係を定量評価したいと考えています。",
        request: "貸与する試作ハンドを使い、指定の評価プロトコルに沿って把持実験を行い、データを統計処理して評価レポートを作成してください。",
        deliverables: ["実験データ(生データ+整理済み)", "評価レポート", "改善への示唆"],
        knowledge: ["実験計画の基礎", "統計処理(平均・ばらつき)", "力覚センサの扱い"],
        equipment: ["学校の実験室", "貸与される試作ハンド・センサ類"],
        cautions: ["駆動部に手を近づけない", "実験は必ず教員立会いのもとで実施"],
        criteria: ["実験の再現性", "データ整理の適切さ", "考察の深さ"],
        referenceMaterialIds: ["m6", "m14"],
        companyRating: 4.9,
        companyRatingCount: 3,
        submissionTemplateId: "t2",
        learnPoints: "最先端のロボット開発に、評価エンジニアとして参加できるレアクエストです。",
        ndaRequired: true,
    },
    {
        id: "q12",
        title: "ベアリング周辺の異音原因の調査整理",
        company: "白山機工株式会社",
        industry: "産業機械組立",
        difficulty: 4,
        recommendedGrade: "4年生以上",
        requiredSkills: ["materials", "machining", "report"],
        reward: 14000,
        xp: 230,
        deadline: "2026-09-25",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "出荷後の装置でベアリング周辺から異音がするというクレームが散発しています。原因候補を体系的に整理した資料が社内にありません。",
        request: "提供する故障事例メモと組立図をもとに、異音の原因候補をツリー状に整理し、切り分け手順を提案してください。",
        deliverables: ["原因分析ツリー(なぜなぜ図)", "切り分け手順書"],
        knowledge: ["転がり軸受の構造と損傷モード", "はめあいと予圧の基礎"],
        equipment: ["自宅または学校のPC"],
        cautions: ["顧客名など固有情報は資料から削除済みです"],
        criteria: ["原因候補の網羅性", "切り分け手順の論理性"],
        referenceMaterialIds: ["m4", "m5"],
        companyRating: 4.0,
        companyRatingCount: 7,
        submissionTemplateId: "t7",
        learnPoints: "トラブルシューティングの論理的な進め方を実例で学べます。",
        ndaRequired: true,
    },
    {
        id: "q13",
        title: "板金カバーのコストダウン設計案",
        company: "北陸溶接工業株式会社",
        industry: "溶接・板金",
        difficulty: 3,
        recommendedGrade: "3年生以上",
        requiredSkills: ["cad", "machining", "drawing"],
        reward: 11000,
        xp: 170,
        deadline: "2026-09-10",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "装置用の板金カバーが溶接主体の構造でコストが高く、曲げ加工中心の構造に見直したいと考えています。",
        request: "現行カバーの図面をもとに、溶接箇所を減らし曲げで成立させる構造案を検討し、展開図のラフ案まで作成してください。",
        deliverables: ["構造見直し提案書", "展開図ラフ案"],
        knowledge: ["板金の曲げ加工の基礎", "最小曲げ半径", "溶接と曲げのコスト感覚"],
        equipment: ["自宅または学校のPC", "CADソフト(任意)"],
        cautions: ["外形寸法と取付穴位置は変更不可"],
        criteria: ["コスト削減効果", "組立やすさ", "図面の正確さ"],
        referenceMaterialIds: ["m9", "m10"],
        companyRating: 4.2,
        companyRatingCount: 5,
        submissionTemplateId: "t5",
        learnPoints: "板金設計の「曲げで作る」発想と、コスト意識が身につきます。",
        ndaRequired: false,
    },
    {
        id: "q14",
        title: "検査工程の記録をスプレッドシートで自動集計",
        company: "エヌテック計測株式会社",
        industry: "計測・検査",
        difficulty: 2,
        recommendedGrade: "2年生以上",
        requiredSkills: ["aidx", "report"],
        reward: 7000,
        xp: 110,
        deadline: "2026-08-15",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        isPopular: true,
        classmatesChallenging: 4,
        background: "検査記録を毎日手作業でExcelに転記・集計しており、月末の集計に丸1日かかっています。",
        request: "サンプルデータをもとに、関数・ピボットテーブル(または簡単なスクリプト)で自動集計される集計シートを作成してください。",
        deliverables: ["自動集計シート", "使い方の説明書(1〜2ページ)"],
        knowledge: ["表計算の関数(VLOOKUP/SUMIFS等)", "データの正規化の考え方"],
        equipment: ["自宅または学校のPC"],
        cautions: ["マクロを使う場合は動作環境を明記すること"],
        criteria: ["集計の正確さ", "担当者が保守できるシンプルさ"],
        referenceMaterialIds: ["m14"],
        companyRating: 4.8,
        companyRatingCount: 21,
        submissionTemplateId: "t8",
        learnPoints: "現場の困りごとをITで解決する、DX案件の入門編です。",
        ndaRequired: false,
    },
    {
        id: "q15",
        title: "モータ軸のキー溝設計チェック",
        company: "加賀オートメーション株式会社",
        industry: "FA・自動化設備",
        difficulty: 3,
        recommendedGrade: "3年生以上",
        requiredSkills: ["materials", "drawing", "machining"],
        reward: 9000,
        xp: 150,
        deadline: "2026-09-01",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: false,
        approvalStatus: "approved",
        isTeam: false,
        background: "減速機とモータをつなぐ軸まわりで、キーの規格選定が設計者ごとにバラバラになっており、標準化したいと考えています。",
        request: "JISのキー規格を調査し、当社でよく使う軸径(φ10〜φ40)に対するキー選定早見表と、設計チェックリストを作成してください。",
        deliverables: ["キー選定早見表", "設計チェックリスト"],
        knowledge: ["JIS B 1301(キー及びキー溝)", "軸のトルク伝達の基礎"],
        equipment: ["自宅または学校のPC"],
        cautions: ["規格の引用元(規格番号・年度)を明記すること"],
        criteria: ["規格の正確な引用", "早見表の使いやすさ"],
        referenceMaterialIds: ["m5", "m2"],
        companyRating: 4.5,
        companyRatingCount: 8,
        submissionTemplateId: "t8",
        learnPoints: "JIS規格を調べて使いこなす、設計実務の基本動作が身につきます。",
        ndaRequired: false,
    },
    /* ---------- 教員承認待ちクエスト(5件) ---------- */
    {
        id: "p1",
        title: "旋盤加工サンプルの表面粗さ測定",
        company: "小松マシンパーツ株式会社",
        industry: "機械加工",
        difficulty: 2,
        recommendedGrade: "3年生以上",
        requiredSkills: ["measurement", "machining", "report"],
        reward: 6000,
        xp: 100,
        deadline: "2026-09-30",
        remoteOk: false,
        safetyLevel: "中",
        dangerLabels: ["学校設備使用", "工具使用あり"],
        teacherCheckRequired: true,
        approvalStatus: "pending",
        isTeam: false,
        background: "切削条件と表面粗さの関係を整理した社内データが不足しています。",
        request: "送付する加工サンプル12個の表面粗さを学校の粗さ計で測定し、切削条件との関係をまとめてください。",
        deliverables: ["粗さ測定データ", "条件と粗さの関係グラフ"],
        knowledge: ["表面粗さパラメータ(Ra/Rz)", "旋削加工の基礎"],
        equipment: ["学校の表面粗さ測定機"],
        cautions: ["測定機の使用は教員の許可を得ること"],
        criteria: ["測定の再現性", "グラフのわかりやすさ"],
        referenceMaterialIds: ["m11", "m6"],
        companyRating: 4.3,
        companyRatingCount: 6,
        submissionTemplateId: "t4",
        learnPoints: "加工条件と品質の関係を、実測データで理解できます。",
        ndaRequired: false,
    },
    {
        id: "p2",
        title: "小型プレス機の安全カバー設計",
        company: "ホームテック株式会社",
        industry: "生活用品メーカー",
        difficulty: 4,
        recommendedGrade: "4年生以上",
        requiredSkills: ["cad", "materials", "drawing"],
        reward: 18000,
        xp: 280,
        deadline: "2026-10-15",
        remoteOk: false,
        safetyLevel: "高",
        dangerLabels: ["現場訪問あり", "重量物あり", "教員立会い推奨"],
        teacherCheckRequired: true,
        approvalStatus: "pending",
        isTeam: false,
        background: "社内の小型プレス機に後付けの安全カバーを設置したいが、設計リソースが不足しています。",
        request: "現地採寸のうえ、インターロック付き安全カバーの構想設計と3Dモデルを作成してください。",
        deliverables: ["構想設計書", "3Dモデル", "組立図ラフ"],
        knowledge: ["機械安全の基礎", "インターロックの考え方", "板金設計"],
        equipment: ["企業の工場(採寸)", "学校のPC・CAD"],
        cautions: ["プレス機の操作は行いません", "採寸時は必ず停止・電源遮断状態で実施"],
        criteria: ["安全規格への配慮", "設計の実現性"],
        referenceMaterialIds: ["m9", "m15"],
        companyRating: 4.7,
        companyRatingCount: 10,
        submissionTemplateId: "t1",
        learnPoints: "機械安全という就職後すぐ役立つ知識を、実案件で学べます。",
        ndaRequired: true,
    },
    {
        id: "p3",
        title: "薬品タンク周辺部品の材質調査",
        company: "北陸ケミカル機器株式会社",
        industry: "化学プラント機器",
        difficulty: 3,
        recommendedGrade: "4年生以上",
        requiredSkills: ["materials", "report"],
        reward: 10000,
        xp: 160,
        deadline: "2026-09-28",
        remoteOk: true,
        safetyLevel: "中",
        dangerLabels: ["リモートのみ", "薬品使用あり"],
        teacherCheckRequired: true,
        approvalStatus: "pending",
        isTeam: false,
        background: "薬液タンクの配管サポート部品で腐食が発生し、材質変更を検討しています。",
        request: "対象薬品(資料提供)に対する金属・樹脂材料の耐食性を文献調査し、候補材料の比較表を作成してください。※薬品の実物は扱いません。",
        deliverables: ["耐食性比較表", "推奨材料と根拠"],
        knowledge: ["金属の腐食の基礎", "耐食材料(SUS/樹脂)の特徴"],
        equipment: ["自宅または学校のPC(文献調査のみ)"],
        cautions: ["調査のみで薬品の取り扱いはありません"],
        criteria: ["出典の信頼性", "比較表の網羅性"],
        referenceMaterialIds: ["m1"],
        companyRating: 3.9,
        companyRatingCount: 3,
        submissionTemplateId: "t8",
        learnPoints: "材料選定の調査プロセスを実務レベルで経験できます。",
        ndaRequired: true,
    },
    {
        id: "p4",
        title: "協働ロボット導入前の作業分析",
        company: "未来ロボティクス株式会社",
        industry: "ロボット開発",
        difficulty: 3,
        recommendedGrade: "3年生以上",
        requiredSkills: ["aidx", "control", "report"],
        reward: 12000,
        xp: 190,
        deadline: "2026-10-05",
        remoteOk: false,
        safetyLevel: "中",
        dangerLabels: ["現場訪問あり", "回転体あり"],
        teacherCheckRequired: true,
        approvalStatus: "pending",
        isTeam: false,
        background: "取引先工場への協働ロボット導入にあたり、対象工程の作業分析データが必要です。",
        request: "工場見学(1日)で組立工程を観察し、作業を要素分解して、ロボット化しやすい工程・しにくい工程を整理してください。",
        deliverables: ["作業分析シート", "ロボット化適性の評価表"],
        knowledge: ["作業分析(時間研究)の基礎", "協働ロボットの特徴"],
        equipment: ["取引先工場(見学)", "学校のPC"],
        cautions: ["稼働中の設備には近づかない", "写真撮影は許可されたエリアのみ"],
        criteria: ["分析の粒度", "評価の論理性"],
        referenceMaterialIds: ["m15"],
        companyRating: 4.9,
        companyRatingCount: 3,
        submissionTemplateId: "t6",
        learnPoints: "ロボットSIerの上流工程(工程分析)を体験できます。",
        ndaRequired: true,
    },
    {
        id: "p5",
        title: "AIによる外観検査の教師データ作成と精度検証",
        company: "エヌテック計測株式会社",
        industry: "計測・検査",
        difficulty: 4,
        recommendedGrade: "4年生以上",
        requiredSkills: ["aidx", "measurement", "report"],
        reward: 16000,
        xp: 260,
        deadline: "2026-10-20",
        remoteOk: true,
        safetyLevel: "低",
        dangerLabels: ["リモートのみ"],
        teacherCheckRequired: true,
        approvalStatus: "pending",
        isTeam: false,
        background: "樹脂部品の外観検査AIを試験導入中ですが、教師データの品質が精度に与える影響を検証できていません。",
        request: "支給する画像データ500枚にラベル付けを行い、ラベル品質と検出精度の関係を検証レポートにまとめてください。",
        deliverables: ["ラベル付きデータセット", "精度検証レポート"],
        knowledge: ["画像分類の基礎", "混同行列と精度指標"],
        equipment: ["自宅または学校のPC"],
        cautions: ["画像データの再配布禁止"],
        criteria: ["ラベルの一貫性", "検証方法の妥当性"],
        referenceMaterialIds: ["m14"],
        companyRating: 4.8,
        companyRatingCount: 21,
        submissionTemplateId: "t7",
        learnPoints: "製造業×AIの最前線である外観検査AIの開発工程に触れられます。",
        ndaRequired: true,
    },
];
const QUEST_MAP = Object.fromEntries(QUESTS.map((q) => [q.id, q]));

/* ---------- materials ---------- */
/** 学習教材15件(10カテゴリをカバー) */
const MATERIALS = [
    {
        id: "m1",
        title: "応力とひずみの基礎 — 「壊れない」を計算する",
        category: "材料力学",
        difficulty: 2,
        minutes: 25,
        xp: 50,
        skillIds: ["materials"],
        relatedQuestIds: ["q6", "p3"],
        summary: "引張・圧縮・せん断の3つの基本応力と、応力-ひずみ線図の読み方を学びます。降伏点・引張強さ・安全率の関係を、身近な部品の例で理解します。",
        quiz: {
            question: "断面積100mm²の丸棒に10kNの引張荷重が作用するとき、引張応力はいくらか?",
            choices: ["10 MPa", "100 MPa", "1000 MPa", "1 MPa"],
            answerIndex: 1,
            explanation: "応力 = 荷重 ÷ 断面積 = 10,000 N ÷ 100 mm² = 100 N/mm² = 100 MPa です。",
        },
    },
    {
        id: "m2",
        title: "はりのたわみ計算 — 片持ちはりと単純支持はり",
        category: "材料力学",
        difficulty: 3,
        minutes: 35,
        xp: 70,
        skillIds: ["materials"],
        relatedQuestIds: ["q6", "q15"],
        summary: "設計で最も出番の多い「はりのたわみ公式」を、片持ちはり・単純支持はりの代表パターンで整理。断面二次モーメントの意味と、たわみを減らす設計の考え方まで学びます。",
        quiz: {
            question: "片持ちはりの先端集中荷重によるたわみは、はりの長さLの何乗に比例するか?",
            choices: ["1乗", "2乗", "3乗", "4乗"],
            answerIndex: 2,
            explanation: "δ = PL³/(3EI) より、たわみは長さの3乗に比例します。長さが2倍になるとたわみは8倍です。",
        },
    },
    {
        id: "m3",
        title: "ボルトの強度区分と締付けトルクの基本",
        category: "ボルト・ナット",
        difficulty: 2,
        minutes: 20,
        xp: 45,
        skillIds: ["materials", "drawing"],
        relatedQuestIds: ["q7", "q6"],
        summary: "「4.8」「10.9」などの強度区分の読み方、軸力と締付けトルクの関係、緩み止めの基本を学びます。ボルト選定チェックの実務にも直結する内容です。",
        quiz: {
            question: "強度区分10.9のボルトの引張強さはいくらか?",
            choices: ["109 MPa", "900 MPa", "1000 MPa", "1090 MPa"],
            answerIndex: 2,
            explanation: "前半の「10」が引張強さ1000MPa(10×100)を表し、後半の「.9」は降伏比0.9を表します。",
        },
    },
    {
        id: "m4",
        title: "転がり軸受の選び方と寿命計算入門",
        category: "軸・ベアリング",
        difficulty: 3,
        minutes: 30,
        xp: 60,
        skillIds: ["materials", "machining"],
        relatedQuestIds: ["q12"],
        summary: "深溝玉軸受と円筒ころ軸受の使い分け、基本動定格荷重と寿命(L10寿命)の計算、はめあい・予圧の基礎を学びます。異音トラブルの原因理解にも役立ちます。",
        quiz: {
            question: "玉軸受の寿命は荷重の何乗に反比例するか?",
            choices: ["1乗", "2乗", "3乗", "10/3乗"],
            answerIndex: 2,
            explanation: "玉軸受の寿命 L10 =(C/P)³ × 10⁶回転。荷重Pが2倍になると寿命は1/8になります。",
        },
    },
    {
        id: "m5",
        title: "キーとキー溝 — 軸のトルク伝達の定番",
        category: "軸・ベアリング",
        difficulty: 2,
        minutes: 20,
        xp: 45,
        skillIds: ["drawing", "machining"],
        relatedQuestIds: ["q15"],
        summary: "平行キーによるトルク伝達の仕組みと、JIS B 1301に基づく軸径ごとのキー寸法の選び方を学びます。キー溝の図面指示と加工方法もあわせて確認します。",
        quiz: {
            question: "平行キーが主に受ける応力はどれか?",
            choices: ["引張応力", "せん断応力と面圧", "曲げ応力のみ", "熱応力"],
            answerIndex: 1,
            explanation: "キーはトルク伝達時に側面の面圧と断面のせん断で力を受けます。設計ではこの2つを検討します。",
        },
    },
    {
        id: "m6",
        title: "ノギス・マイクロメータの正しい使い方",
        category: "公差・はめあい",
        difficulty: 1,
        minutes: 15,
        xp: 35,
        skillIds: ["measurement"],
        relatedQuestIds: ["q3", "q11", "p1"],
        summary: "測定器の読み方だけでなく、測定力・温度・アッベの原理といった「誤差の原因」まで理解します。測定値の信頼性を語れるようになるための第一歩です。",
        quiz: {
            question: "マイクロメータで測定力を一定にするための機構はどれか?",
            choices: ["バーニヤ", "ラチェットストップ", "クランプ", "アンビル"],
            answerIndex: 1,
            explanation: "ラチェットストップが空転することで、誰が測っても一定の測定力になるよう設計されています。",
        },
    },
    {
        id: "m7",
        title: "はめあい記号(H7/g6)を完全理解する",
        category: "公差・はめあい",
        difficulty: 3,
        minutes: 30,
        xp: 60,
        skillIds: ["drawing", "machining"],
        relatedQuestIds: ["q1", "q12"],
        summary: "すきまばめ・しまりばめ・中間ばめの違いと、H7/g6などの記号の読み方を学びます。ベアリングのはめあい選定など、実務での使いどころも紹介します。",
        quiz: {
            question: "φ20 H7/g6 のはめあいはどれに分類されるか?",
            choices: ["しまりばめ", "すきまばめ", "中間ばめ", "圧入"],
            answerIndex: 1,
            explanation: "H穴基準に対しg軸は常にすきまができる位置にあるため、すきまばめです。回転・摺動部に使われます。",
        },
    },
    {
        id: "m8",
        title: "シーケンス制御とPLCの基礎",
        category: "機械要素",
        difficulty: 3,
        minutes: 40,
        xp: 75,
        skillIds: ["control", "electronics"],
        relatedQuestIds: ["q9", "p4"],
        summary: "自己保持回路・インターロックなどシーケンス制御の基本パターンと、PLCのI/O割付・ラダー図の読み方を学びます。制御盤案件の前提知識になります。",
        quiz: {
            question: "押しボタンを離してもモータが回り続けるようにする基本回路はどれか?",
            choices: ["インターロック回路", "自己保持回路", "タイマ回路", "非常停止回路"],
            answerIndex: 1,
            explanation: "出力の接点で自分自身の入力を保持する「自己保持回路」がシーケンス制御の最重要パターンです。",
        },
    },
    {
        id: "m9",
        title: "板金設計入門 — 曲げで作る、を身につける",
        category: "板金設計",
        difficulty: 3,
        minutes: 35,
        xp: 65,
        skillIds: ["cad", "machining"],
        relatedQuestIds: ["q13", "p2"],
        summary: "最小曲げ半径・曲げの展開長・穴と曲げ線の距離など、板金設計の基本ルールを学びます。溶接構造を曲げ構造に置き換えるコストダウンの考え方も扱います。",
        quiz: {
            question: "曲げ線の近くに穴があると起こる問題はどれか?",
            choices: ["穴が変形する", "板が硬くなる", "塗装が剥がれる", "溶接できなくなる"],
            answerIndex: 0,
            explanation: "曲げ変形の影響で穴が引っ張られて変形します。一般に板厚の2.5〜3倍以上離すのが目安です。",
        },
    },
    {
        id: "m10",
        title: "溶接記号と溶接部の設計の基本",
        category: "溶接設計",
        difficulty: 3,
        minutes: 30,
        xp: 60,
        skillIds: ["drawing", "machining"],
        relatedQuestIds: ["q2", "q13"],
        summary: "すみ肉溶接・開先溶接の使い分け、図面上の溶接記号の読み方、熱変形への配慮を学びます。溶接治具の役割についても触れます。",
        quiz: {
            question: "すみ肉溶接の強度計算で基準とする断面はどこか?",
            choices: ["脚長部", "のど断面", "母材断面", "ビード表面"],
            answerIndex: 1,
            explanation: "すみ肉溶接は最小断面である「のど断面」で強度を評価します。のど厚 a ≒ 0.7×脚長です。",
        },
    },
    {
        id: "m11",
        title: "切削加工の基礎 — 旋盤・フライス・工具の常識",
        category: "加工方法",
        difficulty: 2,
        minutes: 30,
        xp: 55,
        skillIds: ["machining"],
        relatedQuestIds: ["q8", "p1"],
        summary: "旋削とフライス加工の違い、切削速度・送り・切込みの3要素、エンドミルの内隅Rの制約など、設計者が知っておくべき加工の基礎知識をまとめます。",
        quiz: {
            question: "エンドミル加工でポケットの内隅に必ず残るものは何か?",
            choices: ["バリ", "工具半径によるR", "テーパ", "段差"],
            answerIndex: 1,
            explanation: "回転工具で加工するため、内隅には工具半径以上のRが必ず残ります。ピン角が必要なら別工程が必要です。",
        },
    },
    {
        id: "m12",
        title: "3Dプリンタの造形制約とデータ修正",
        category: "加工方法",
        difficulty: 2,
        minutes: 25,
        xp: 50,
        skillIds: ["cad", "machining"],
        relatedQuestIds: ["q4", "q8"],
        summary: "FDM方式の最小肉厚・オーバーハング角度・サポートの考え方と、STLデータでよくある不備(面の破れ・非多様体)の直し方を学びます。",
        quiz: {
            question: "FDM方式でサポートなしに造形しやすいオーバーハング角度の目安はどれか?",
            choices: ["垂直から15°まで", "垂直から45°まで", "垂直から80°まで", "角度は関係ない"],
            answerIndex: 1,
            explanation: "一般に垂直から45°程度までがサポートなしで造形できる目安とされています(材料・機種で変動)。",
        },
    },
    {
        id: "m13",
        title: "図面の読み方① 三角法と寸法記入の基本",
        category: "図面の読み方",
        difficulty: 1,
        minutes: 20,
        xp: 40,
        skillIds: ["drawing"],
        relatedQuestIds: ["q1", "q7"],
        summary: "第三角法の投影の仕組み、正面図の選び方、寸法補助記号(φ・R・C・t)の意味を学びます。図面を「見る」から「読める」への第一歩です。",
        quiz: {
            question: "寸法数値の前につく「C2」はどんな指示か?",
            choices: ["半径2mmの丸み", "45°の面取り2mm", "板厚2mm", "穴の深さ2mm"],
            answerIndex: 1,
            explanation: "Cは45°面取り(Chamfer)を表します。C2は「2mmの45°面取り」の指示です。",
        },
    },
    {
        id: "m14",
        title: "実験データの整理と統計の基本",
        category: "設計レビュー",
        difficulty: 2,
        minutes: 25,
        xp: 50,
        skillIds: ["measurement", "report", "aidx"],
        relatedQuestIds: ["q3", "q11", "q14", "p5"],
        summary: "平均・標準偏差・ヒストグラムによるばらつきの見える化と、グラフで伝わるレポートの作り方を学びます。測定・実験系クエストの必修教材です。",
        quiz: {
            question: "測定データのばらつきの大きさを表す代表的な指標はどれか?",
            choices: ["平均値", "最頻値", "標準偏差", "中央値"],
            answerIndex: 2,
            explanation: "標準偏差はデータが平均のまわりにどれだけ散らばっているかを表す、ばらつきの基本指標です。",
        },
    },
    {
        id: "m15",
        title: "設計レビューとリスクアセスメント入門",
        category: "設計レビュー",
        difficulty: 3,
        minutes: 30,
        xp: 60,
        skillIds: ["report", "teamdev"],
        relatedQuestIds: ["q10", "q2", "q5", "p2", "p4"],
        summary: "設計レビューで何を見るべきか、指摘の伝え方、リスクアセスメント(危険源の特定→リスク見積り→低減)の基本手順を学びます。安全レビュー系クエストの土台になります。",
        quiz: {
            question: "リスク低減の3ステップ方式で最優先すべき対策はどれか?",
            choices: ["保護具の着用", "警告表示", "本質的安全設計", "作業者教育"],
            answerIndex: 2,
            explanation: "危険源そのものをなくす「本質的安全設計」が最優先。ガードや表示・教育はその次の手段です。",
        },
    },
];
const MATERIAL_MAP = Object.fromEntries(MATERIALS.map((m) => [m.id, m]));
const MATERIAL_CATEGORIES = [
    "材料力学",
    "機械要素",
    "ボルト・ナット",
    "軸・ベアリング",
    "公差・はめあい",
    "板金設計",
    "溶接設計",
    "加工方法",
    "図面の読み方",
    "設計レビュー",
];

/* ---------- misc ---------- */
/** バッジ10種類 */
const BADGES = [
    { id: "b1", name: "ギルド入門", icon: "🎖️", rarity: "コモン", description: "MechaXMatchに登録して冒険を始めた" },
    { id: "b2", name: "はじまりの学び", icon: "📖", rarity: "コモン", description: "はじめて教材の学習を完了した" },
    { id: "b3", name: "初クエスト達成", icon: "⚔️", rarity: "コモン", description: "はじめてクエストを完了した" },
    { id: "b4", name: "3日連続ログイン", icon: "🔥", rarity: "コモン", description: "3日連続で学習・クエストに取り組んだ" },
    { id: "b5", name: "知識コレクター", icon: "📚", rarity: "レア", description: "教材を5個以上学習完了した" },
    { id: "b6", name: "クエストハンター", icon: "🏹", rarity: "レア", description: "クエストを3件以上完了した" },
    { id: "b7", name: "レベル5到達", icon: "⭐", rarity: "レア", description: "レベル5に到達した" },
    { id: "b8", name: "チームプレイヤー", icon: "🤝", rarity: "レア", description: "チームクエストに参加申請した" },
    { id: "b9", name: "教員承認済みの実績", icon: "✅", rarity: "エピック", description: "教員承認済みクエストを完了した(安全に配慮できる証)" },
    { id: "b10", name: "企業に選ばれし者", icon: "👑", rarity: "レジェンド", description: "企業評価バッジ:企業から高評価(平均4.5以上)を獲得した" },
    { id: "b11", name: "見習い技術者ライセンス", icon: "🪪", rarity: "レア", description: "工学倫理・機密情報・安全管理の講習を修了し、企業クエストの受注資格を得た" },
];
/** 称号(レベル帯で変化) */
const TITLES = [
    { minLevel: 1, title: "見習いエンジニア" },
    { minLevel: 3, title: "ギルドの新星" },
    { minLevel: 5, title: "ジュニア技士" },
    { minLevel: 8, title: "熟練クラフター" },
    { minLevel: 12, title: "マスターエンジニア" },
    { minLevel: 16, title: "ギルドの重鎮" },
    { minLevel: 20, title: "伝説の技術者" },
];
function titleForLevel(level) {
    let title = TITLES[0].title;
    for (const t of TITLES)
        if (level >= t.minLevel)
            title = t.title;
    return title;
}
/** ダミー広告6件 */
const ADS = [
    { id: "ad1", category: "CADソフト", icon: "🖥️", color: "#a78bfa", title: "Fusion CAD 学生版が無料", body: "高専生なら3D CADが無料で使い放題。クエストの武器を手に入れよう。", cta: "無料で始める" },
    { id: "ad2", category: "3Dプリンタ", icon: "🖨️", color: "#22d3ee", title: "学割3Dプリンタ MX-Mini", body: "寮の机に置けるコンパクト設計。試作クエストが捗る一台。", cta: "学割価格を見る" },
    { id: "ad3", category: "工具", icon: "🔧", color: "#fb923c", title: "エンジニア工具セット", body: "現役設計者が選んだ工具22点。最初の一式はこれで決まり。", cta: "セット内容を見る" },
    { id: "ad4", category: "技術書", icon: "📘", color: "#4ade80", title: "『機械設計の基礎と実務』", body: "教科書と現場のギャップを埋める一冊。クエスト攻略本としても◎。", cta: "試し読み" },
    { id: "ad5", category: "インターン", icon: "🏭", color: "#f472b6", title: "高専生向け夏インターン特集", body: "クエスト実績がそのまま応募資料になる企業を厳選しました。", cta: "特集を見る" },
    { id: "ad6", category: "資格講座", icon: "🎓", color: "#fbbf24", title: "機械設計技術者試験 対策講座", body: "3級合格でスキルツリーも一気に成長。今なら学割50%OFF。", cta: "講座の詳細" },
];
/** 今週のランキング8人分(自分を除くダミー学生) */
const RANKING = [
    { name: "アオイ@機械5年", department: "機械工学科", grade: "5年", weeklyXp: 1240, level: 14 },
    { name: "ハヤト@電気4年", department: "電気電子工学科", grade: "4年", weeklyXp: 1105, level: 12 },
    { name: "ミナミ@情報3年", department: "情報工学科", grade: "3年", weeklyXp: 980, level: 11 },
    { name: "リク@機械4年", department: "機械工学科", grade: "4年", weeklyXp: 870, level: 10 },
    { name: "サクラ@物質2年", department: "物質化学工学科", grade: "2年", weeklyXp: 760, level: 8 },
    { name: "ソウタ@機械3年", department: "機械工学科", grade: "3年", weeklyXp: 640, level: 9 },
    { name: "ユイ@電気5年", department: "電気電子工学科", grade: "5年", weeklyXp: 555, level: 13 },
    { name: "カイト@情報2年", department: "情報工学科", grade: "2年", weeklyXp: 430, level: 6 },
];
/** デイリーミッション定義(毎日3件) */
const DAILY_QUESTS = [
    { id: "d1", title: "教材を1つ学習完了する", xp: 20, icon: "📖" },
    { id: "d2", title: "クエストを1件チェックする", xp: 10, icon: "🔍" },
    { id: "d3", title: "スキルツリーを確認して目標を決める", xp: 10, icon: "🌳" },
];
/** ウィークリーミッション(条件を満たすと報告してボーナスXP) */
const WEEKLY_MISSIONS = [
    { id: "w1", title: "今週の獲得経験値 400 XP", xp: 80, icon: "⚡", metric: "weeklyXp", target: 400 },
    { id: "w2", title: "学習済み教材を累計 8 本にする", xp: 60, icon: "📚", metric: "materials", target: 8 },
    { id: "w3", title: "デイリーミッションを1日で全達成", xp: 50, icon: "🎯", metric: "dailyAll", target: 3 },
];
/** 全国高専ランキング(ダミー) */
const NATIONAL_RANKING = [
    { name: "レン@明石高専", department: "機械工学科", grade: "5年", weeklyXp: 2350, level: 21 },
    { name: "ツバサ@木更津高専", department: "電子制御工学科", grade: "4年", weeklyXp: 2210, level: 19 },
    { name: "ヒナタ@熊本高専", department: "情報通信エレクトロニクス工学科", grade: "5年", weeklyXp: 2080, level: 20 },
    { name: "イツキ@仙台高専", department: "総合工学科", grade: "3年", weeklyXp: 1930, level: 15 },
    { name: "アカリ@奈良高専", department: "機械工学科", grade: "4年", weeklyXp: 1820, level: 17 },
    { name: "ソラ@苫小牧高専", department: "創造工学科", grade: "5年", weeklyXp: 1700, level: 18 },
    { name: "ナギ@高知高専", department: "ソーシャルデザイン工学科", grade: "2年", weeklyXp: 1610, level: 11 },
    { name: "アオイ@機械5年", department: "機械工学科(あなたの高専)", grade: "5年", weeklyXp: 1240, level: 14 },
];
/** スキル別ランキング(CAD部門・ダミー) */
const SKILL_RANKING = {
    skillName: "CAD",
    entries: [
        { name: "アオイ@機械5年", department: "機械工学科", grade: "5年", weeklyXp: 640, level: 8 },
        { name: "リク@機械4年", department: "機械工学科", grade: "4年", weeklyXp: 520, level: 7 },
        { name: "ミナミ@情報3年", department: "情報工学科", grade: "3年", weeklyXp: 410, level: 6 },
        { name: "ソウタ@機械3年", department: "機械工学科", grade: "3年", weeklyXp: 350, level: 5 },
        { name: "サクラ@物質2年", department: "物質化学工学科", grade: "2年", weeklyXp: 220, level: 4 },
    ],
};
/** 期間限定イベント(ダミー) */
const LIMITED_EVENT = {
    title: "夏の実装フェス 2026",
    description: "期間中、学習教材の獲得XPが1.5倍!夏休みにスキルツリーを一気に伸ばそう。",
    until: "2026-08-31",
    icon: "🎆",
};
/** 企業からのスカウト風カード(ダミー) */
const SCOUTS = [
    {
        id: "sc1",
        company: "未来ロボティクス株式会社",
        message: "レポート作成スキルLv.3以上のあなたに、評価実験クエストへの招待が届いています。",
        questId: "q11",
        icon: "🤖",
    },
    {
        id: "sc2",
        company: "株式会社タカハシ精機",
        message: "前回の図面CAD化の丁寧な仕事ぶりを見て、続編クエストのご指名です。",
        questId: "q7",
        icon: "🏭",
    },
];
/** アバター候補(プロフィールで選択) */
const AVATARS = ["🧑‍🔧", "👩‍🔧", "🧑‍💻", "👩‍💻", "🧑‍🏭", "🦾", "🤖", "⚙️"];
/** ログインボーナスの宝箱報酬テーブル(ランダム報酬) */
const CHEST_REWARDS = [
    { name: "ブロンズの歯車", xp: 15, weight: 50 },
    { name: "シルバーの歯車", xp: 30, weight: 30 },
    { name: "ゴールドの歯車", xp: 60, weight: 15 },
    { name: "✨レジェンドコア✨", xp: 120, weight: 5 },
];

/* ---------- team ---------- */
/** チームクエスト5件(複数学科での協働案件) */
const TEAM_QUESTS = [
    {
        id: "tq1",
        title: "小型AGV(無人搬送車)の試作開発",
        company: "加賀オートメーション株式会社",
        description: "工場内の部品搬送を想定した小型AGVのプロトタイプを、機構・回路・制御・ソフトの分担で開発します。月1回の企業レビューあり。",
        reward: 120000,
        xp: 1200,
        deadline: "2026-12-20",
        approvalStatus: "approved",
        dangerLabels: ["学校設備使用", "工具使用あり", "回転体あり", "教員立会い推奨"],
        roles: [
            { name: "機械設計担当", requiredSkills: ["cad", "materials"], capacity: 2, members: ["リク@機械4年"] },
            { name: "電気回路担当", requiredSkills: ["electronics"], capacity: 2, members: ["ハヤト@電気4年"] },
            { name: "制御担当", requiredSkills: ["control"], capacity: 1, members: [] },
            { name: "ソフトウェア担当", requiredSkills: ["aidx"], capacity: 2, members: ["ミナミ@情報3年"] },
            { name: "レポート担当", requiredSkills: ["report"], capacity: 1, members: [] },
        ],
    },
    {
        id: "tq2",
        title: "工場向けIoT電力見える化システム",
        company: "白山機工株式会社",
        description: "工場設備の消費電力をセンサで収集し、ダッシュボードで見える化するシステムを構築。省エネ改善の提案までがゴールです。",
        reward: 80000,
        xp: 800,
        deadline: "2026-11-30",
        approvalStatus: "approved",
        dangerLabels: ["現場訪問あり", "高電圧注意", "教員立会い推奨"],
        roles: [
            { name: "電気回路担当", requiredSkills: ["electronics"], capacity: 2, members: ["ユイ@電気5年"] },
            { name: "ソフトウェア担当", requiredSkills: ["aidx"], capacity: 2, members: [] },
            { name: "実験・計測担当", requiredSkills: ["measurement"], capacity: 1, members: [] },
            { name: "プレゼン担当", requiredSkills: ["report", "teamdev"], capacity: 1, members: ["サクラ@物質2年"] },
        ],
    },
    {
        id: "tq3",
        title: "介護用ベッドサイド手すりの改良設計",
        company: "ホームテック株式会社",
        description: "利用者の声をもとに、既存手すりの強度・使いやすさを改良します。強度試験と人間工学的な評価をチームで実施します。",
        reward: 60000,
        xp: 600,
        deadline: "2026-11-15",
        approvalStatus: "approved",
        dangerLabels: ["学校設備使用", "重量物あり"],
        roles: [
            { name: "機械設計担当", requiredSkills: ["cad", "drawing"], capacity: 2, members: ["アオイ@機械5年"] },
            { name: "実験・計測担当", requiredSkills: ["measurement", "materials"], capacity: 2, members: [] },
            { name: "レポート担当", requiredSkills: ["report"], capacity: 1, members: [] },
        ],
    },
    {
        id: "tq4",
        title: "廃校プールを活用した水中ドローン実証実験",
        company: "未来ロボティクス株式会社",
        description: "開発中の水中点検ドローンの実証実験をチームで運営。実験計画の立案からデータ解析、報告会でのプレゼンまで担当します。",
        reward: 100000,
        xp: 1000,
        deadline: "2027-01-31",
        approvalStatus: "approved",
        dangerLabels: ["現場訪問あり", "教員立会い推奨"],
        roles: [
            { name: "制御担当", requiredSkills: ["control"], capacity: 1, members: [] },
            { name: "実験・計測担当", requiredSkills: ["measurement"], capacity: 2, members: ["ソウタ@機械3年"] },
            { name: "ソフトウェア担当", requiredSkills: ["aidx"], capacity: 1, members: [] },
            { name: "プレゼン担当", requiredSkills: ["report", "teamdev"], capacity: 1, members: [] },
        ],
    },
    {
        id: "tq5",
        title: "商店街のレトロ看板をLED化するプロジェクト",
        company: "北陸電機制御株式会社",
        description: "地元商店街の老朽化した看板をLED化。意匠を守りつつ、配線設計・制御・施工図面までをチームで手がける地域連携クエストです。",
        reward: 50000,
        xp: 500,
        deadline: "2026-10-31",
        approvalStatus: "approved",
        dangerLabels: ["現場訪問あり", "高電圧注意", "工具使用あり", "教員立会い推奨"],
        roles: [
            { name: "電気回路担当", requiredSkills: ["electronics"], capacity: 2, members: ["カイト@情報2年"] },
            { name: "機械設計担当", requiredSkills: ["cad", "machining"], capacity: 1, members: [] },
            { name: "制御担当", requiredSkills: ["control"], capacity: 1, members: [] },
            { name: "レポート担当", requiredSkills: ["report"], capacity: 1, members: [] },
        ],
    },
];
const TEAM_QUEST_MAP = Object.fromEntries(TEAM_QUESTS.map((t) => [t.id, t]));

/* ---------- templates ---------- */
/** 成果物提出テンプレート8件 */
const TEMPLATES = [
    {
        id: "t1",
        name: "CADデータ提出テンプレート",
        icon: "🖥️",
        purpose: "3Dモデル・図面データを、企業がそのまま確認・利用できる形で提出するためのテンプレートです。",
        fields: ["使用CADソフトとバージョン", "モデリング方針(基準面・原点の取り方)", "ファイル一覧と内容説明", "未確定・推測した箇所の一覧", "確認してほしいポイント"],
        fileFormats: ["STEP (.step/.stp)", "ネイティブデータ (.f3d/.sldprt等)", "2D図面PDF"],
        evaluationPoints: ["寸法の正確さ", "モデルツリーの整理", "推測箇所を正直に申告しているか"],
        sampleEntry: "使用ソフト: Fusion 360 (2026年6月版) / 原点は図面の基準面Aに設定。φ12穴の深さが図面から読み取れなかったため、貫通と仮定しました(要確認リスト No.2 参照)。",
    },
    {
        id: "t2",
        name: "実験レポートテンプレート",
        icon: "🔬",
        purpose: "実験の目的から考察まで、第三者が再現できるレベルで実験を報告するためのテンプレートです。",
        fields: ["目的", "実験方法(装置・条件・手順)", "結果(表・グラフ)", "考察", "誤差要因", "結論と今後の課題"],
        fileFormats: ["PDF", "元データのExcel/CSV"],
        evaluationPoints: ["再現可能な方法の記述", "グラフの適切さ", "考察が結果に基づいているか"],
        sampleEntry: "目的: 把持力と対象物損傷の関係を定量化する。方法: 試作ハンドで卵型サンプルを把持し、力覚センサ値と表面損傷スコアを記録(n=10×5条件)。",
    },
    {
        id: "t3",
        name: "設計レビューシート",
        icon: "✅",
        purpose: "設計内容や選定結果を、チェック観点ごとにレビューして報告するためのテンプレートです。",
        fields: ["レビュー対象", "チェック観点リスト", "指摘事項(重要度つき)", "改善提案", "判定(OK/条件付きOK/NG)"],
        fileFormats: ["PDF", "Excel"],
        evaluationPoints: ["観点の網羅性", "指摘の根拠(計算・規格)", "重要度づけの妥当性"],
        sampleEntry: "指摘No.3【重要度:高】M8ボルト4本の合計許容せん断荷重に対し、想定荷重の安全率が1.4と低い。強度区分10.9への変更またはM10化を提案する(計算根拠は別紙2)。",
    },
    {
        id: "t4",
        name: "寸法測定レポート",
        icon: "📏",
        purpose: "測定値を、使用計測器・条件・ばらつきとセットで信頼できる形で報告するためのテンプレートです。",
        fields: ["使用計測器(管理番号・校正状態)", "測定環境(温度)", "測定箇所の図示", "測定データ表", "統計値(平均・標準偏差)", "公差に対する判定"],
        fileFormats: ["Excel", "PDF"],
        evaluationPoints: ["測定条件の明記", "データの整理のわかりやすさ", "判定の正確さ"],
        sampleEntry: "計測器: デジタルノギス(校正2026/04)。測定箇所①外径φ20±0.05 → 平均20.012 / σ=0.008 / 20個全数公差内(判定:合格)。",
    },
    {
        id: "t5",
        name: "加工改善提案書",
        icon: "⚙️",
        purpose: "「作りにくい」を「作りやすい」に変える提案を、Before/Afterで説得力をもって伝えるテンプレートです。",
        fields: ["現状の問題点(加工性・コスト)", "改善案(Before/Afterスケッチ)", "機能への影響評価", "期待効果(時間・コスト)", "リスクと確認事項"],
        fileFormats: ["PDF", "PowerPoint"],
        evaluationPoints: ["問題点の的確さ", "機能を損なわない配慮", "効果の定量化"],
        sampleEntry: "問題点: 内隅R0指示のポケットは放電加工が必要でコスト大。改善案: 機能上支障のない内隅にR3を付与し、エンドミル加工のみで完結(加工時間 約40%減の見込み)。",
    },
    {
        id: "t6",
        name: "作業手順書テンプレート",
        icon: "📋",
        purpose: "初めての人でも安全に作業を再現できる手順書を作るためのテンプレートです。",
        fields: ["作業の目的と完成状態", "必要な工具・保護具", "手順(1ステップ1動作+写真)", "危険ポイント(目立つ表記)", "品質チェックポイント"],
        fileFormats: ["PowerPoint", "PDF"],
        evaluationPoints: ["手順の抜け漏れのなさ", "初心者へのわかりやすさ", "安全注意の明示"],
        sampleEntry: "手順12: ベアリングを軸に挿入する。⚠️危険: プレス使用時は必ず治具で垂直を保持(斜め圧入は破損の恐れ)。チェック: 挿入後、手で回して引っかかりがないこと。",
    },
    {
        id: "t7",
        name: "不具合再現レポート",
        icon: "🐛",
        purpose: "不具合の状況と再現条件を整理し、原因調査につなげるためのテンプレートです。",
        fields: ["不具合の概要", "発生条件・頻度", "再現手順", "原因候補の整理(ツリー)", "切り分け結果", "推定原因と対策案"],
        fileFormats: ["PDF", "Excel"],
        evaluationPoints: ["再現手順の具体性", "原因候補の網羅性", "論理的な切り分け"],
        sampleEntry: "発生条件: 回転数1200rpm以上かつ無負荷時のみ異音発生(10回中8回)。原因候補ツリーより、はめあい不良(軸側公差外れ)を最有力と推定。",
    },
    {
        id: "t8",
        name: "技術調査レポート",
        icon: "🔎",
        purpose: "規格・材料・技術動向などの調査結果を、出典つきで信頼できる形にまとめるテンプレートです。",
        fields: ["調査の目的と範囲", "調査方法(出典リスト)", "調査結果(比較表)", "考察・推奨案", "参考文献(規格番号・年度)"],
        fileFormats: ["PDF", "Word"],
        evaluationPoints: ["出典の信頼性", "比較表の網羅性", "結論の明確さ"],
        sampleEntry: "出典: JIS B 1301:2009。軸径φ25に対する平行キーは 8×7(幅×高さ)。比較表では軸径φ10〜φ40の6区分を整理した(表2参照)。",
    },
];
const TEMPLATE_MAP = Object.fromEntries(TEMPLATES.map((t) => [t.id, t]));

/* ---------- reviews ---------- */
/** 企業→学生の評価データ5件 */
const COMPANY_REVIEWS = [
    {
        id: "cr1",
        company: "エヌテック計測株式会社",
        questTitle: "機械部品の寸法測定レポート作成",
        techUnderstanding: 4, deadlineCompliance: 5, reporting: 5, quality: 4, rehireIntent: 5,
        comment: "測定条件まできちんと記録されており、社内の新人より丁寧でした。手順書への指摘も的確で助かりました。",
    },
    {
        id: "cr2",
        company: "株式会社タカハシ精機",
        questTitle: "古い手描き図面を3D CAD化する",
        techUnderstanding: 4, deadlineCompliance: 4, reporting: 4, quality: 5, rehireIntent: 5,
        comment: "不明寸法を推測せず質問してくれた姿勢が素晴らしい。モデルツリーも整理されていて即戦力レベルです。",
    },
    {
        id: "cr3",
        company: "株式会社プロトラボ金沢",
        questTitle: "3Dプリンタ用データの修正・最適化",
        techUnderstanding: 3, deadlineCompliance: 5, reporting: 4, quality: 4, rehireIntent: 4,
        comment: "納期より2日早い提出。修正メモがわかりやすく、そのまま社内ナレッジに使わせてもらいました。",
    },
    {
        id: "cr4",
        company: "白山機工株式会社",
        questTitle: "工場の作業手順を動画から手順書に整理",
        techUnderstanding: 4, deadlineCompliance: 3, reporting: 4, quality: 4, rehireIntent: 4,
        comment: "中間報告が1回遅れたのは残念でしたが、完成した手順書は現場でそのまま使える品質でした。",
    },
    {
        id: "cr5",
        company: "加賀オートメーション株式会社",
        questTitle: "搬送ユニットの簡易強度計算",
        techUnderstanding: 5, deadlineCompliance: 5, reporting: 5, quality: 5, rehireIntent: 5,
        comment: "前提条件の整理が的確で、計算書は設計部の様式に近い完成度。ぜひ次の案件もお願いしたいです。",
    },
];
/** 学生→企業の評価データ5件 */
const STUDENT_REVIEWS = [
    {
        id: "sr1",
        company: "エヌテック計測株式会社",
        questTitle: "機械部品の寸法測定レポート作成",
        clarity: 5, responseSpeed: 5, rewardFairness: 4, learning: 4, safetyCare: 5, recommend: 5,
        comment: "質問への返信が当日中で安心でした。測定の意味まで説明してもらえて勉強になりました。",
    },
    {
        id: "sr2",
        company: "株式会社タカハシ精機",
        questTitle: "古い手描き図面を3D CAD化する",
        clarity: 4, responseSpeed: 4, rewardFairness: 5, learning: 5, safetyCare: 5, recommend: 5,
        comment: "実物の図面を扱えるのが貴重な経験。作業量に対して報酬も妥当だと感じました。",
    },
    {
        id: "sr3",
        company: "北陸溶接工業株式会社",
        questTitle: "溶接治具の改善案を考える",
        clarity: 3, responseSpeed: 3, rewardFairness: 4, learning: 5, safetyCare: 5, recommend: 4,
        comment: "依頼範囲が途中で少し広がったのが大変でしたが、現場見学は最高に勉強になりました。保護具の準備も万全でした。",
    },
    {
        id: "sr4",
        company: "白山機工株式会社",
        questTitle: "ベアリング周辺の異音原因の調査整理",
        clarity: 4, responseSpeed: 3, rewardFairness: 4, learning: 4, safetyCare: 4, recommend: 4,
        comment: "資料が充実していて調査しやすかったです。返信は2〜3日かかることがありました。",
    },
    {
        id: "sr5",
        company: "未来ロボティクス株式会社",
        questTitle: "【レア】ロボットハンド試作機の評価実験",
        clarity: 5, responseSpeed: 5, rewardFairness: 5, learning: 5, safetyCare: 5, recommend: 5,
        comment: "実験計画のレビューを毎週してもらえて、研究室レベルの学びがありました。安全手順も徹底していました。",
    },
];

/* ---------- tutorial ---------- */
const TUTORIAL_MODULES = [
    {
        id: "ethics",
        title: "工学倫理",
        icon: "⚖️",
        color: "#22d3ee",
        intro: "君の書く1本の線、1つの数値が、実際の製品や現場につながる。技術者ギルドの一員として、まず「技術者の責任」を心に刻もう。",
        points: [
            "技術者の仕事は社会に影響する — 課題の先に「使う人」がいることを忘れない",
            "安全性を軽視しない — 「たぶん大丈夫」で進めない",
            "わからないことを隠さない — 正直に「わからない」と言えるのがプロ",
            "データを改ざんしない — 都合の悪い結果こそ価値のある情報",
            "できないことを「できる」と言わない — 過大な約束は事故のもと",
            "利益より安全を優先する — 迷ったら安全側に倒す",
        ],
    },
    {
        id: "confidential",
        title: "機密情報の取り扱い",
        icon: "🔐",
        color: "#a78bfa",
        intro: "企業クエストでは、外に出せない図面・データを預かることがある。信頼を一度失うと、君だけでなく学校全体がクエストを受けられなくなる。",
        points: [
            "企業名・図面・写真・測定データを勝手に公開しない",
            "SNSに投稿しない — 「一部だけ」「加工すれば」もNG",
            "生成AIに機密情報を入力しない — 入力した瞬間に社外流出と同じ",
            "個人PCや私物USBに保存しない — 指定された保存場所だけを使う",
            "共有範囲を確認する — 「誰まで見てよいか」を最初に確認",
            "不明な場合は教員・企業に確認する — 自己判断が一番危険",
        ],
    },
    {
        id: "safety",
        title: "安全管理",
        icon: "🦺",
        color: "#4ade80",
        intro: "ものづくりの現場には本物の危険がある。ケガをしない・させないことは、どんな成果物よりも優先される。",
        points: [
            "工具・回転体・高電圧・薬品・重量物には危険度ラベルで注意",
            "危険作業は必ず教員の許可を取る",
            "ひとり作業禁止の案件は必ず複数人+立会いで実施する",
            "保護具(保護メガネ・安全靴・手袋など)を正しく使用する",
            "学校設備のルールを遵守する — 使用許可・清掃・返却まで",
            "無理な納期を受けない — 焦りは事故と品質低下の原因",
        ],
    },
    {
        id: "communication",
        title: "企業とのコミュニケーション",
        icon: "💬",
        color: "#fbbf24",
        intro: "企業が一番困るのは「音信不通」。うまくできることより、こまめに正直に伝えられることが信頼につながる。",
        points: [
            "依頼内容を勝手に解釈しない — 認識合わせをしてから着手する",
            "不明点は早めに質問する — 質問は迷惑ではなく歓迎される",
            "進捗を定期的に報告する — 順調なときも報告する",
            "納期遅れの可能性は早めに伝える — 直前の報告が一番の信頼失墜",
            "成果物の前提条件を書く — 「何を仮定したか」を必ず添える",
            "言葉遣いは丁寧にする — 相手は取引先。友達言葉はNG",
        ],
    },
    {
        id: "quality",
        title: "成果物の品質",
        icon: "📐",
        color: "#f472b6",
        intro: "よい成果物とは「他人が再現・検証できる」成果物。天才的なひらめきよりも、丁寧な記録が評価される。",
        points: [
            "単位を明記する — 数値だけのデータは使えない",
            "前提条件を明記する — 荷重条件・材質・環境温度など",
            "参考資料・出典を書く — 規格番号・年度まで正確に",
            "測定条件を書く — 使用計測器・校正状態・測定環境",
            "CAD・図面・レポートの版数(バージョン)を管理する",
            "再現できる形で提出する — 手順どおりやれば同じ結果になること",
        ],
    },
];
/** ミニテスト(6問・4択・80%以上=5問正解で合格) */
const TUTORIAL_QUIZ = [
    {
        question: "企業から受け取った図面の一部を「勉強の記録」としてSNSに投稿してよいか?",
        choices: [
            "図面の一部だけならよい",
            "モザイク加工すればよい",
            "いかなる形でも投稿してはいけない",
            "企業名を伏せればよい",
        ],
        answerIndex: 2,
        explanation: "一部・加工済み・企業名なしでも機密漏洩になり得ます。企業から預かった情報はいかなる形でも公開してはいけません。",
    },
    {
        question: "生成AIに企業の未公開図面や測定データを入力してよいか?",
        choices: [
            "便利なので積極的に使う",
            "入力してはいけない(社外への流出と同じ)",
            "無料のAIでなければよい",
            "結果を共有しなければよい",
        ],
        answerIndex: 1,
        explanation: "生成AIへの入力は社外サーバへの送信です。機密情報の入力は流出と同じ扱いになります。使う場合は企業・教員の許可が必要です。",
    },
    {
        question: "測定結果が想定と大きく違ったとき、どうするべきか?",
        choices: [
            "想定に合うように数値を調整する",
            "違ったデータは削除して報告しない",
            "そのまま記録し、条件を添えて正直に報告する",
            "都合のよいデータだけ選んで報告する",
        ],
        answerIndex: 2,
        explanation: "データの改ざん・選別は技術者として最もやってはいけない行為です。想定外の結果こそ、条件とともに正直に報告しましょう。",
    },
    {
        question: "作業中に「危ない」と感じる作業を頼まれたら、どうするべきか?",
        choices: [
            "断ると評価が下がるので我慢してやる",
            "作業を止め、教員・企業に相談する",
            "こっそりひとりで素早く済ませる",
            "動画を見て自己流でやってみる",
        ],
        answerIndex: 1,
        explanation: "危険を感じたら止まる・相談するが鉄則です。安全は成果物よりも報酬よりも優先されます。断ることは評価を下げません。",
    },
    {
        question: "納期に間に合わなそうだと気づいたとき、どうするべきか?",
        choices: [
            "気づいた時点ですぐ企業と教員に相談する",
            "納期当日に謝罪する",
            "間に合わせるために品質チェックを省く",
            "黙って徹夜で何とかする",
        ],
        answerIndex: 0,
        explanation: "遅れの可能性は早く伝えるほど対策の選択肢が増えます。直前報告・品質省略・無理な徹夜はすべて信頼と安全を損ないます。",
    },
    {
        question: "レポートに測定値を書くとき、正しいのはどれか?",
        choices: [
            "数値だけを大きく書く",
            "単位・測定条件・使用計測器も明記する",
            "きりのよい数値に丸めて書く",
            "うまくいった測定だけを書く",
        ],
        answerIndex: 1,
        explanation: "他人が再現・検証できることが品質の基本です。単位・前提条件・測定条件・計測器の情報を必ず添えましょう。",
    },
];
const TUTORIAL_PASS_RATE = 0.8;
const TUTORIAL_PASS_XP = 300;
